class Urls:
    main_site = 'https://stellarburgers.nomoreparties.site/'
    url_login = f'{main_site}login'
    url_profile = f'{main_site}account/profile'
    url_profile_order_history = f'{main_site}account/order-history'
    url_register = f'{main_site}register'
    url_restore = f'{main_site}forgot-password'
    url_reset = f'{main_site}reset-password'
    url_history = f'{main_site}account/order-history'
    url_feed = f'{main_site}feed'